FROM apache/airflow:2.7.3-python3.10

ENV AIRFLOW_HOME=/opt/airflow \
	PIP_NO_CACHE_DIR=1

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
	curl && \
	rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY dags/ /opt/airflow/dags

CMD ["airflow", "scheduler"]
